### ISSUE TITLE
Docker for UIB without data volume container 

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah#2]
1. Switch to cantara zulu (which use debian instead of centos) https://github.com/Cantara/maven-infrastructure/blob/master/zulu/Dockerfile 
2. Compare existing environment setup with current environment set up by ansible. 
3. Discuss need for sshd 
4. Document how to use the image.

**Comment by totto** [comment]
As of now... the startup and update scripts for this dockerfile is located in a sub-directory of the docker config in this repo...  those scripts should probably be located with the UIB repo and wget raw-referenced into the docker files upon running them..   the scripts are also used in the bootstrap scripts in the root of this repo which will now fail as the old referenced scripts in UIB is now "gone"
