### ISSUE TITLE
Review Whydah REST endpoint using OWASP recommendations 

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah#4]
https://www.owasp.org/index.php/REST_Security_Cheat_Sheet

Burde kanskje dokumentere Whydah i context av de anbefalingene der?
Tenker spesielt på å beskrive ticket/tokens og hvordan de sendes. 

"XML should never be built by string concatenation. It should always be constructed using an XML serializer. This ensures that the XML content sent to the browser is parseable and does not contain XML injection. For more information, please see the Web Service Security Cheat Sheet. "

**Comment by totto** [comment]
From the OWASP recommendations:  This rule can easily provide versioning nightmare..  " Strongly type incoming data as quickly as possible."
